packages:
  - "apps/*"
  - "packages/*"

overrides:
  flatted: 3.4.2

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
blockExoticSubdeps: true
strictDepBuilds: true
strictPeerDependencies: true
allowBuilds:
  esbuild: true
